# Reference https://render-web.onrender.com/docs/blueprint-spec

databases:
  - name: rails_demo_7-db
    plan: free
    ipAllowList: [] # only allow connections from services in this Render account

services:
  - type: web
    name: rails_demo_7-web
    plan: free # optional (defaults to starter)
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_demo_7-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: rails_demo_7-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        generateValue: true

  - type: redis
    name: rails_demo_7-redis
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lru # optional (defaults to allkeys-lru)
    ipAllowList: [] # only allow internal connections
